# PYTHIA configuration file.
# Generated on Mon Apr 18 13:20:41 CDT 2016 with the user supplied options:
# --enable-shared

# Install directory prefixes.
PREFIX_BIN=/storage/icn/aortizve/software/64bits/pythia8212/bin
PREFIX_INCLUDE=/storage/icn/aortizve/software/64bits/pythia8212/include
PREFIX_LIB=/storage/icn/aortizve/software/64bits/pythia8212/lib
PREFIX_SHARE=/storage/icn/aortizve/software/64bits/pythia8212/share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=true
CXX=g++
CXX_COMMON=-O2 -ansi -pedantic -W -Wall -Wshadow -fPIC
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=true
FASTJET3_BIN=/storage/icn/aortizve/software/64bits/fastjet-3.1.3/instalacion/bin
FASTJET3_INCLUDE=/storage/icn/aortizve/software/64bits/fastjet-3.1.3/instalacion/include
FASTJET3_LIB=/storage/icn/aortizve/software/64bits/fastjet-3.1.3/instalacion/lib

# HEPMC2 configuration.
HEPMC2_USE=false
HEPMC2_BIN=
HEPMC2_INCLUDE=
HEPMC2_LIB=

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=
LHAPDF5_PLUGIN=LHAPDF5.h

# LHAPDF6 configuration.
LHAPDF6_USE=false
LHAPDF6_BIN=
LHAPDF6_INCLUDE=
LHAPDF6_LIB=
LHAPDF6_PLUGIN=LHAPDF5.h

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=true
ROOT_BIN=/storage/icn/aortizve/software/64bits/alicesw/root/alice_v5-34-30/inst/bin/
ROOT_INCLUDE=/storage/icn/aortizve/software/64bits/alicesw/root/alice_v5-34-30/inst/include/
ROOT_LIB=/storage/icn/aortizve/software/64bits/alicesw/root/alice_v5-34-30/inst/lib/

# GZIP configuration.
GZIP_USE=false
GZIP_BIN=
GZIP_INCLUDE=
GZIP_LIB=

# BOOST configuration.
BOOST_USE=false
BOOST_BIN=
BOOST_INCLUDE=
BOOST_LIB=
